public class Address {
    public void homeAddress(){
        string myName = 'Fariza';
        system.debug('my name is ' + myName);

        integer numberOfMembers = 4;
        system.debug('total number if members in my family is ' + numberOfmembers);

        string houseName = 'Kelsey';
        system.debug(houseName);

        integer houseNumber = 9018;
        system.debug(houseNumber);

        string streetName = 'Kelsey';
        system.debug(streetName);

        string cityName = 'Houston';
        system.debug(cityName);

        string stateName = 'Texas';
        system.debug(stateName);

        string stateIsoCode = 'TX';
        system.debug(stateIsoCode);

        string countryName = 'United States';
        system.debug(countryName);

        string countryIsoCode = 'US';
        system.debug(countryIsoCode);

        integer zipCode = 77379;
        system.debug(zipCode);

        boolean isYourHome = true;
        system.debug(isYourHome);

    }
}
